services:
  - type: web
    name: bfhl-fastapi
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker main:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
